### ISSUE TITLE
(commutative)MonoidLaws Tests pass when they shouldn't

### ISSUE THREAD

**Issue by asciola** [twitter/algebird#357] opened 2014-11-14 22:26 UTC
This monoid:
```scala
class RandomMonoid[T: ClassTag](implicit semi: Semigroup[T]) extends Monoid[Array[T]] {
  override def zero = Array[T]()
  override def plus(left: Array[T], right: Array[T]) = {
    if (scala.util.Random.nextBoolean) right else left
  }
}
```

Passes this test:
```scala
 property("Random Monoid laws") {
    monoidLaws[Array[String]]
  }
```

**Comment by sritchie** [comment] 2016-10-24 20:31
Do we know if this is still an issue?

**Comment by sritchie** [comment] 2016-10-24 20:39
Yup, duplicate of #528

**Closed by sritchie** 2016-10-24 20:39 UTC
Labels: bug, testing
