### ISSUE TITLE
Approximate collections API.

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#44] opened 2012-12-04 02:01 UTC
There is something going on with some of the data-structures we have here: BloomFilter is a kind of approximate Set. HyperLogLog is an approximate set with Cardinality. Count-min-sketch is an approximate Map (so Count-min-sketch has an approximate set on the keys).

I think we could define a few traits to represent these concepts.

Something like:

``` scala
trait ApproximateSet[V] {
  def mayContain(v: V): Boolean
  def containsFalsePosProb: Double
  def containsFalseNegProb: Double
}
```

In fact, most of these have false neg prob == 0.0, so maybe we should encode that in the type (for cases where you want to be sure you don't miss anything).

``` scala
trait ApproxAcceptingSet[V] extends ApproximateSet[V] {
  final def containsFalseNegProb = 0.0
}
```

Maybe we want to punt and avoid the returning the false negatives, and if we want to support set union (which these as monoids would have):

``` scala
trait ApproximateSet[V,S<:ApproximateSet[V,S]] {
  // if we return false, the item is definitely NOT in this set.
  def mayContain(v: V): Boolean
  // f-bounded polymorphism to preserve the types:
  def union(that: S): S
}
```

For size, maybe something like:

``` scala
trait ApproximateCardinality {
  def approxSize: Long
}
```

For Count-min-sketch, it looks like we need something like:

``` scala
trait ApproximateMap[K,V] {
  def approxValue(k: K): Option[V]
}
```

In this view, I think CMS extends ApproximateMap, BloomFilter extends ApproximateSet, and HyperLogLog extends ApproximateSet with ApproximateCardinality

**Comment by sritchie-stripe** [comment] 2016-10-29 13:01
I THINK this may be a duplicate of `Approximate.scala`. Thoughts?

**Comment by sritchie** [comment] 2016-10-29 13:02
I THINK that we can close this now that we have `Approximate.scala` - thoughts?

**Comment by sritchie** [comment] 2016-11-18 14:44
Moved discussion to #465

**Closed by sritchie** 2016-11-18 14:44 UTC
Labels: on-close-alert
